### ISSUE TITLE
Help with fixing pathing in MISE

### ISSUE THREAD

**Issue by Hexaae** [bgbennyboy/Monkey-Island-Explorer#1]
Hi,
sorry to be a bit off-topic but I couldn't find other way to contact you...
Was wondering if you know how to fix player "pathing" on screen, to fix incorrect sprite positioning (sigh this game development was so lazy...). For example in this image below you can see how Guybrush is badly positioned too up "into the doorway":

![The Secret Of Monkey Island Special Edition Screenshot 2024 01 02 - 19 59 05 45](https://github.com/bgbennyboy/Monkey-Island-Explorer/assets/8591462/efd4fc2b-f10b-4208-9a92-0237ab928277)

I fixed a bunch of gfx glitches with your tools ( https://steamcommunity.com/sharedfiles/filedetails/?id=3128072912 ) and wondered if you could help me fixing these too...

**Comment by bgbennyboy** [comment]
For future reference, there's a contact form on my website :)

Its been a very long time since I looked at the special editions so I don't know. I would assume its using the walkboxes from the original game. If it is using different walkboxes then they'd most likely be stored in the *.xml files. But my guess is that its the originals.

**Comment by Hexaae** [comment]
Ok ;)
Uh... so it's most likely shared with the classic data? Mmmh wouldn't be a good idea trying to edit that to fix one version and break the other.

BTW, last thing since you know a lot about the technical aspects of MI: there is a known workaround to use the classic version localized (not English only), i.e. put under \classic\en\ the classic localized game files Monkey1.000 and .001, and it does work, but... at this point SE edition won't show non-english chars like the Italian accented vowels (à,è,ì,ò,ù...) correctly! Do you know how this is managed internally? Where is the codeset defined... I wish there was a way to have both SE and Classic work fine and localized...

**Comment by bgbennyboy** [comment]
I dont know, like I say its been years. There were a number of translations, so perhaps one of those translation groups has solved it.
